version: "3.10"

services:

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    command:
      - server
    ports:
      - "8800:8200"
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

    environment:
      VAULT_ADDR: https://0.0.0.0:8200
      VAULT_API_ADDR: https://vault:8200
      VAULT_CLUSTER_ADDR: https://vault:8201
      VAULT_LOCAL_CONFIG: |
        listener "tcp" {
          address = "0.0.0.0:8200"
          cluster_address = "0.0.0.0:8201"
          tls_disable = 0
          tls_cert_file = "/vault/config/certs/cert.pem"
          tls_key_file = "/vault/config/certs/key.pem"
        }
        storage "file" {
          path = "/vault/data"
        }
        api_addr = "http://vault:8200"
        cluster_addr = "https://vault:8201"
        ui = true
    volumes:
      - "./vault:/vault/data"
      - "./certs:/vault/config/certs"
